name: Deploy to Server

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |                              #TODO add IP and add path
          ssh -o "StrictHostKeyChecking=no" root@${{ secrets.SSH_DEV_HOST }} << 'ENDSSH'
          cd /home/${{ secrets.SSH_DIR_PATH }}
          docker compose --env-file docker/.env.dev -f ./docker/dev.yml down
          git checkout develop
          git pull
          docker compose --env-file docker/.env.dev -f ./docker/dev.yml up -d --build
          ENDSSH